version: '3.1'
services:
  mysql:
    container_name: parenting_sim_mysql
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: parenting_sim
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: