spring:
  config:
    import:
      - classpath:./application-db.yml
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-message: always
    include-stacktrace: never